prostages_accueil:
   path: /
   controller: App\Controller\ProstagesController::index


listeEntreprises:
  path: /entreprises
  controller: App\Controller\ProstagesController::listeEntreprises

detailEntreprise:
  path: /entreprise/{id}
  controller: App\Controller\ProstagesController::detailEntreprise

stagesParEntreprise:
  path: /stages_entreprise/{id}
  controller: App\Controller\ProstagesController::stagesParEntreprise

  

listeFormations:
  path: /formations
  controller: App\Controller\ProstagesController::listeFormations

detailFormation:
  path: /formation/{id}
  controller: App\Controller\ProstagesController::detailFormation

stagesParFormation:
  path: /stages_formation/{id}
  controller: App\Controller\ProstagesController::stagesParFormation





listeStages:
  path: /stages
  controller: App\Controller\ProstagesController::listeStages

detailStage:
  path: /stage/{id}
  controller: App\Controller\ProstagesController::detailStage

formationsParStage:
  path: /formations_stage/{id}
  controller: App\Controller\ProstagesController::formationsParStage