prostages_accueil:
   path: /
   controller: App\Controller\ProstagesController::index

listeEntreprises:
  path: /entreprises
  controller: App\Controller\ProstagesController::listeEntreprises

detailEntreprise:
  path: /entreprise/{id}
  controller: App\Controller\ProstagesController::detailEntreprise

listeFormations:
  path: /formations
  controller: App\Controller\ProstagesController::listeFormations

detailFormation:
  path: /formation/{id}
  controller: App\Controller\ProstagesController::detailFormation

listeStages:
  path: /stages
  controller: App\Controller\ProstagesController::listeStages

detailStage:
  path: /stage/{id}
  controller: App\Controller\ProstagesController::detailStage