prostages_accueil:
   path: /
   controller: App\Controller\ProstagesController::index

entreprises:
  path: /entreprises
  controller: App\Controller\ProstagesController::entreprises

formations:
  path: /formations
  controller: App\Controller\ProstagesController::formations

listeStages:
  path: /stages
  controller: App\Controller\ProstagesController::listeStages

detailStage:
  path: /stage/{id}
  controller: App\Controller\ProstagesController::detailStage